#!/bin/bash
#
# qwc	control quattor-web-console
#
### BEGIN INIT INFO
# Provides: qwc
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $syslog $network
# Should-Stop: $syslog $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Short-Description: quattor-web-console
# Description: Quattor Web Console Daemon
### END INIT INFO

# Source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="quattor-web-console"
pidfile=/var/run/$prog.pid
conffile="/etc/$prog/config.ini"
logfile=/var/log/$prog.log
lockfile=/var/lock/subsys/$prog
paster=/usr/local/aquilon/pythonenv/bin/paster

start() {
    if [[ -x $paster ]]; then
        echo -n "Starting quattor web console: "
        if [[ $UID -ne 0 ]]; then
            RETVAL=1
            failure
        else
            $paster serve --log-file=$logfile --pid-file=$pidfile $conffile --daemon
            RETVAL=$?
            if [[ $RETVAL -eq 0 ]]; then
                touch $lockfile
                success
            fi
        fi
        echo 
        return $RETVAL
    else
        exit 5
    fi
}

stop() {
    echo -n "Stopping quattor web console: "
    if [ $UID -ne 0 ]; then
        RETVAL=1
        failure
    else
        killproc -p $pidfile $paster
        RETVAL=$?
        if [[ $RETVAL -eq 0 ]]; then
            rm -f $lockfile
        fi
    fi
    echo
    return $RETVAL
}

restart(){
    stop
    start
}

qwcstatus(){
    status qwc >/dev/null 2>&1
}

# See how we were called.
case "$1" in
    start)
        qwcstatus && exit 0
        start
        RETVAL=$?
        ;;
    stop)
        qwcstatus || exit 0
        stop
        RETVAL=$?
        ;;
    restart)
        restart
        RETVAL=$?
        ;;
    force-reload)
        restart
        RETVAL=$?
        ;;
    status)
        status -p $pidfile qwc
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|force-reload}"
        RETVAL=2
esac

exit $RETVAL
